### ISSUE TITLE
无法正确加载/卸载本插件

### ISSUE THREAD

**Issue by ph59x** [kmcsr/smart_backup_mcdr#1]
# 描述：
只有使用`!!MCDR plugin enable SmartBackup-v1.4.2.mcdr`时插件可以加载
其他情况插件无法加载/卸载，命令无法注册
**使用`!!MCDR plugin disable smart_backup`卸载插件后定时备份仍会执行，但执行时只会关闭服务器自动保存(执行`/save-off`和`/save-all`指令)**

# 环境：
Linux 5.10.0-21(Debian11)
Python 3.9.2
Minecraft 1.19.3 Fabirc 0.14.14
MCDR 2.7.2
## MCDR插件
 - AdvancedCalculator (advanced_calculator@0.3.1)
 - Bot (bot@1.0.6)
 - MCDR Command Exporter (command_exporter@1.1.0)
 - Dict Command Registration (dict_command_registration@1.1.0)
 - Here (here@1.2.2)
 - Let Me Click and Send (let_me_click_and_send@1.0.0)
 - Location Marker (location_marker@1.3.1)
 - Task (mcd_task@2.3.5+build.67)
 - MCDReforged (mcdreforged@2.7.2)
 - Minecraft Data API (minecraft_data_api@1.4.1)
 - MoreCommandNodes (more_command_nodes@1.1.0)
 - Quick Backup Multi (quick_backup_multi@1.7.0)

# 输出：
## 开服时:
```
[MCDR] [10:43:05] [TaskExecutor/INFO] [smart_backup]: [SMB] Smart backup is on LOAD
[MCDR] [10:43:05] [TaskExecutor/INFO] [smart_backup]: 配置文件已加载
[MCDR] [10:43:05] [TaskExecutor/INFO] [smart_backup]: 配置文件已加载
[MCDR] [10:43:05] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=smart_backup@1.4.2,priority=1000,callback=<function on_load at 0x7f4a5084d670>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_manager.py", line 589, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/__init__.py", line 13, in on_load
    GL.init(server)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/globals.py", line 152, in init
    c(server)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/api.py", line 47, in on_load
    _flush_backup_timer()
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/api.py", line 35, in _flush_backup_timer
    broadcast_message('Next backup time: ' +
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/utils.py", line 146, in broadcast_message
    MCDR.ServerInterface.get_instance().broadcast(join_rtext(prefix, *args, sep=sep))
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/server_interface.py", line 356, in broadcast
    self.say(text, encoding=encoding)
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/server_interface.py", line 344, in say
    command = self.__server_handler.get_broadcast_message_command(text, self.get_server_information())
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/handler/impl/abstract_minecraft_handler.py", line 71, in get_broadcast_message_command
    return self.get_send_message_command('@a', message, server_information)
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/handler/impl/abstract_minecraft_handler.py", line 60, in get_send_message_command
    version = Version(server_information.version.split(' ')[0])
AttributeError: 'NoneType' object has no attribute 'split'
```
## 关服时
```
[MCDR] [10:40:31] [TaskExecutor/INFO] [smart_backup]: [SMB] Smart backup is on UNLOAD
[MCDR] [10:40:31] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=smart_backup@1.4.2,priority=1000,callback=<function on_unload at 0x7f1fa01fc9d0>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_manager.py", line 589, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/__init__.py", line 18, in on_unload
    GL.destory(server)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/globals.py", line 156, in destory
    if Config is not None:
UnboundLocalError: local variable 'Config' referenced before assignment
```
## 开服后使用`!!MCDR plugin enable SmartBackup-v1.4.2.mcdr`加载插件时
```
[MCDR] [10:35:48] [TaskExecutor/INFO]: 正在从 plugins/SmartBackup-v1.4.2.mcdr.disabled 启用插件
[MCDR] [10:35:48] [TaskExecutor/INFO]: 正在从 plugins/SmartBackup-v1.4.2.mcdr 加载插件
[MCDR] [10:35:48] [TaskExecutor/INFO]: 插件 smart_backup@1.4.2 已加载
[MCDR] [10:35:48] [TaskExecutor/INFO] [smart_backup]: [SMB] Smart backup is on LOAD
[MCDR] [10:35:48] [TaskExecutor/INFO] [smart_backup]: 配置文件已加载
[MCDR] [10:35:48] [TaskExecutor/INFO] [smart_backup]: 配置文件已加载
[MCDR] [10:35:48] [TaskExecutor/INFO] [smart_backup]: [SMB] Next backup time: 2023-03-07 11:35:48
[MCDR] [10:35:48] [TaskExecutor/INFO]: 插件 "SmartBackup-v1.4.2.mcdr.disabled" 启用成功
```

## 开服后使用`!!MCDR plugin disable smart_backup`卸载插件时
```
[MCDR] [10:35:59] [TaskExecutor/INFO]: 正在禁用插件 smart_backup@1.4.2
[MCDR] [10:35:59] [TaskExecutor/INFO]: 正在卸载插件 smart_backup@1.4.2
[MCDR] [10:35:59] [TaskExecutor/INFO]: 插件 smart_backup@1.4.2 已卸载
[MCDR] [10:35:59] [TaskExecutor/INFO] [smart_backup]: [SMB] Smart backup is on UNLOAD
[MCDR] [10:35:59] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=smart_backup@1.4.2,priority=1000,callback=<function on_unload at 0x7f1fa0216700>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_manager.py", line 589, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/__init__.py", line 18, in on_unload
    GL.destory(server)
  File "plugins/SmartBackup-v1.4.2.mcdr/smart_backup/globals.py", line 156, in destory
    if Config is not None:
UnboundLocalError: local variable 'Config' referenced before assignment
```

**Comment by zyxkad** [comment]
感谢反馈，不过目前插件处于重构状态，可能不会立刻解决该问题
